# Generated by Django 3.1.14 on 2022-03-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_info',
            name='gender',
            field=models.CharField(default='male', max_length=50),
            preserve_default=False,
        ),
    ]
